### ISSUE TITLE
Looking for unlimited children hierarchy for chart , not just 5 . Can it be done ?

### ISSUE THREAD

**Issue by bhagyashrijangam** [sgratzl/chartjs-plugin-hierarchical#19]
It would be great if ...

**User story**

**Additional context**

**Comment by sgratzl** [comment]
can you provide an example? There is no limit enforced in the code, so not sure what you mean?

**Comment by bhagyashrijangam** [comment]
Hi @sgratzl  , As highlighted in screenshot Current hierarchies are supported till 5, We wanted to avail it for more than 15 or near to that.  Please check my forked commit which i tried and its working for more than 15. If we can incorporate it in this library that will be great.
<img width="921" alt="Screenshot 2022-11-10 at 7 48 06 PM" src="https://user-images.githubusercontent.com/115703461/201116441-2afc52af-a414-4a4c-8e70-5027e1de5283.png">

https://github.com/sgratzl/chartjs-plugin-hierarchical/commit/2454912db78c2dfcbb08423508666b9ee3e1c996

**Comment by sgratzl** [comment]
happy to review a PR

**Comment by bhagyashrijangam** [comment]
> 
@sgratzl  Here we Go :)

https://github.com/sgratzl/chartjs-plugin-hierarchical/pull/22

**Comment by sgratzl** [comment]
take a look at https://github.com/sgratzl/chartjs-plugin-hierarchical/releases/tag/v3.10.1

**Comment by bhagyashrijangam** [comment]
Yes.. Looks great ! Thanks .
