### ISSUE TITLE
Pluging button overlapping column ticks in vertical charts

### ISSUE THREAD

**Issue by renanzulian** [sgratzl/chartjs-plugin-hierarchical#34]
When I have large descriptions in vertical charts, the button and the line of the plugin ins overlapping the ticks.

**To Reproduce**

1. Add labels with large names

![image](https://user-images.githubusercontent.com/39319636/233168559-d6664168-b442-4796-a092-95f9176b2f06.png)

**Expected behavior**

The same happens with horizontal charts:

![image](https://user-images.githubusercontent.com/39319636/233168735-205c34ee-a4a2-4fef-8ec1-60672ae1cc48.png)

**Context**

- Version: 4.1.1
- Browser: Chrome

**Comment by sgratzl** [comment]
closed with #35
