### ISSUE TITLE
reverse order in the hierarchy

### ISSUE THREAD

**Issue by vwfox** [sgratzl/chartjs-plugin-hierarchical#37]
currently the structure for hierarchies is as follows: The axis always shows the currently lowest level. Below that, the hierarchy descends from the root to the penultimate level. e.g. |E | A - B -C -D
It would be nice to display the tree hierarchically throughout. I understand that it makes sense to display the lowest level on the axis. Therefore there should be a possibility to display the hierarchy as follows: |E| D-C-B-A

**Comment by sgratzl** [comment]
closed via #38
