### ISSUE TITLE
Expand/Collapse all

### ISSUE THREAD

**Issue by clemens1483** [sgratzl/chartjs-plugin-hierarchical#5]
Hi, I really love your plugin - I just had one question: Is there an option to expand/collapse all nodes?

Thank you!

**Comment by sgratzl** [comment]
no there isn't but interesting idea. Where would you place the button and how should it look like?

**Comment by clemens1483** [comment]
Hmh, I think I would probably put it in the top right and make it two separate simple (maybe grey) buttons. But I think even just a function that you can call with a button click outside the chart which sets the `expand?` values of all the nodes to true/false and then just call `chart.update()` would be great. I would imagine there is already an option to hook into the `expand?` value of each individual node?

**Comment by sgratzl** [comment]
when you take a look at the data structure or the example, you'll see that when you define the tree, you can also specify its expand state:

https://github.com/sgratzl/chartjs-plugin-hierarchical#data-structure

https://github.com/sgratzl/chartjs-plugin-hierarchical/blob/master/samples/default.html#L27
