### ISSUE TITLE
Overlapping of legend and Labels.

### ISSUE THREAD

**Issue by vivekburman** [sgratzl/chartjs-plugin-hierarchical#74]
![image](https://github.com/sgratzl/chartjs-plugin-hierarchical/assets/29746680/4bdb0f4a-fdc0-4778-a5ef-ab52a1613f0e)
Hi, as you can see from this image the labels are overlapping the legend. Anyway to fix this?

**Comment by sgratzl** [comment]
have you looked at https://www.chartjs.org/docs/latest/configuration/legend.html#configuration-options to move the legend?
